###############################################################################
# Client configuration
###############################################################################

# Implementation: REST or THRIFT
# Para usar REST:
#ClientEncuestaServiceFactory.className=es.udc.ws.app.client.service.rest.RestClientEncuestaService
# Para usar Thrift (descomentar la siguiente línea y comentar la anterior):
ClientEncuestaServiceFactory.className=es.udc.ws.app.client.service.thrift.ThriftClientEncuestaService

# REST endpoint (Jetty default port 9090)
RestClientEncuestaService.endpointAddress=http://localhost:9090/ws-app-service/

# Thrift endpoint
ThriftClientEncuestaService.endpointAddress=http://localhost:9090/ws-app-service/thrift/encuestaservice
