###############################################################################
# Client configuration
###############################################################################

# Implementation: REST or THRIFT
ClientFactory.className=es.udc.ws.util.rest.client.RestClientFactory

# REST endpoint (Jetty default port 9090)
endpointAddress=http://localhost:9090/ws-app-service

# If using Thrift later, you can set corresponding properties here
