# -----------------------------------------------------------------------------
# Services.
# -----------------------------------------------------------------------------

# AppService implementation (used by factories in ws-util)
AppServiceFactory.className=es.udc.ws.app.model.servicio.ServicioAppImpl

# EncuestaService implementation
EncuestaServicioFactory.className=es.udc.ws.app.model.servicio.EncuestaServicioImpl


# -----------------------------------------------------------------------------
# SqlEncuestaDao.
# -----------------------------------------------------------------------------

SqlEncuestaDaoFactory.className=es.udc.ws.app.model.encuesta.Jdbc3CcSqlEncuestaDao

# -----------------------------------------------------------------------------
# SqlRespuestaDao.
# -----------------------------------------------------------------------------

SqlRespuestaEncuestaDaoFactory.className=es.udc.ws.app.model.respuesta.Jdbc3CcSqlRespuestaEncuestaDao
